-- TABLE_NAME 이라는 테이블의 COLUM이라는 컬럼을 수정
ALTER TABLE TABLE_NAME MODIFY COLUMN_NAME VARCHAR2(4000);

-- 새 컬럼을 생성 (기존 데이터를 옮겨담을 컬럼)
ALTER TABLE TABLE_NAME ADD COLUMN_COPY CLOB;
 
-- 새 컬럼에 기존 데이터를 입력 (SET)
UPDATE TABLE_NAME SET COLUMN_COPY = COLUMN_NAME;
 
-- 기존 컬럼 삭제
ALTER TABLE TABLE_NAME DROP COLUMN COLUMN_NAME;
 
-- 새 컬럼의 이름을 기존 컬럼 이름으로 RENAME
ALTER TABLE TABLE_NAME RENAME COLUMN COLUMN_COPY TO COLUMN_NAME;
